language: node_js

node_js:
  - "node"
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
  - "5"

sudo: false

env:
  - NODE_ENV=test

after_success:
  - 'if [ "${TRAVIS_NODE_VERSION}" = "node" ] ; then make publish-coverage ; fi'
